# Generated by Django 4.1.6 on 2023-03-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('mail', models.EmailField(default='', max_length=30)),
                ('message', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
