# Generated by Django 4.1.6 on 2023-03-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50)),
                ('secondname', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('experience', models.CharField(max_length=50)),
                ('mail', models.EmailField(default='', max_length=30)),
                ('Resume', models.FileField(upload_to='')),
            ],
        ),
    ]
