# Generated by Django 4.1.6 on 2023-03-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('mail', models.EmailField(default='', max_length=30)),
                ('tellAboutUs', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
    ]
